services:
  postgres:
    image: postgres:17
    ports:
      - "45432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brevity
    volumes:
      - postgres_data:/var/lib/postgresql/data

  lgtm:
    image: grafana/otel-lgtm:0.8.6
    ports:
      # For some reason, port 43000 doesn't work on my machine.
      - "43001:3000" # Grafana
      - "44317:4317" # OTLP gRPC
      - "44318:4318" # OTLP HTTP
    volumes:
      - grafana_data:/data/grafana
      - prometheus_data:/data/prometheus
      - loki_data:/data/loki
    environment:
      - GF_PATHS_DATA=/data/grafana

volumes:
  postgres_data:
  grafana_data:
  prometheus_data:
  loki_data:
