mode: dev

database:
  url: "postgres://postgres:postgres@localhost:45432/brevity?sslmode=disable"

llm:
  base_url: "http://localhost:1337/v1/"
  model_id: "lmstudio-community:gemma-3-12b-it-GGUF:gemma-3-12b-it-Q4_K_M.gguf"
  api_key: "PLACEHOLDER_API_KEY"

otel:
  collector_grpc_url: "http://localhost:44317"
