services:
  postgres:
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brevity
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data

  lgtm:
    image: grafana/otel-lgtm:0.8.6
    ports:
      - "3000:3000" # Grafana
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    volumes:
      - grafana_data:/data/grafana
      - prometheus_data:/data/prometheus
      - loki_data:/data/loki
    environment:
      - GF_PATHS_DATA=/data/grafana

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  minio_data:
  grafana_data:
  prometheus_data:
  loki_data:
  redis_data:
