version: '3'

tasks:
  migrate-up:
    desc: Run all pending migrations
    dotenv: 
      - .env
    cmds:
      - go run ./cmd migrate up

  migrate-down:
    desc: Rollback the last migration
    dotenv: 
      - .env
    cmds:
      - go run ./cmd migrate down

  migrate-create:
    desc: Create a new migration
    dotenv: 
      - .env
    requires:
      vars: [NAME]
    cmds:
      - go run ./cmd migrate create {{.NAME}}

  migrate-force:
    desc: Force migration version
    dotenv: 
      - .env
    requires:
      vars: [VERSION]
    cmds:
      - go run ./cmd migrate force {{.VERSION}}

  migrate-version:
    desc: Show current migration version
    dotenv: 
      - .env
    cmds:
      - go run ./cmd migrate version

  migrate-goto:
    desc: Migrate to a specific version
    dotenv: 
      - .env
    requires:
      vars: [VERSION]
    cmds:
      - go run ./cmd migrate goto {{.VERSION}}

  migrate-drop:
    desc: Drop everything in the database
    dotenv: 
      - .env
    cmds:
      - go run ./cmd migrate drop

  server:
    desc: Run the server with OTEL_EXPORTER_OTLP_ENDPOINT set
    dotenv: 
      - .env
    cmds:
      - go run ./cmd server

  s:
    desc: Alias for server
    cmds:
      - task: server

  generate-article:
    desc: Generate a new article for each digital authors.
    dotenv: 
      - .env
    cmds:
      - go run ./cmd generate-article
