name: "OpenAPI Diff"

description: "A GitHub Action to identify differences between Swagger or OpenApi specifications."

inputs:
  base-spec:
    description: "Path to the BASE Swagger or OpenApi specification file."
    required: true
  head-spec:
    description: "Path to the HEAD Swagger or OpenApi specification file."
    required: true

outputs:
  file-name:
    description: "The name of the generated markdown file containing the diff"
    value: ${{ steps.generate_filename.outputs.file-name }}

runs:
  using: "composite"
  steps:
    - id: generate_filename
      name: Generate random filename
      shell: bash
      run: |
        TIMESTAMP=$(date +%s)
        echo "file-name=openapi-diff-$TIMESTAMP.md" >> $GITHUB_OUTPUT
    - name: Run OpenAPI Diff
      uses: docker://openapitools/openapi-diff:2.1.0-beta.12
      # The /github/workspace directory within the container is mapped to the working directory of the action.
      # https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-docker-container-action#accessing-files-created-by-a-container-action
      with:
        args: ${{ inputs.base-spec }} ${{ inputs.head-spec }} --markdown /github/workspace/${{ steps.generate_filename.outputs.file-name }}
