// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package controller

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tuananhlai/brevity-go/internal/store"
)

// NewMockArticleStore creates a new instance of MockArticleStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockArticleStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockArticleStore {
	mock := &MockArticleStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockArticleStore is an autogenerated mock type for the ArticleStore type
type MockArticleStore struct {
	mock.Mock
}

type MockArticleStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockArticleStore) EXPECT() *MockArticleStore_Expecter {
	return &MockArticleStore_Expecter{mock: &_m.Mock}
}

// CreateArticle provides a mock function for the type MockArticleStore
func (_mock *MockArticleStore) CreateArticle(ctx context.Context, article *store.Article) error {
	ret := _mock.Called(ctx, article)

	if len(ret) == 0 {
		panic("no return value specified for CreateArticle")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *store.Article) error); ok {
		r0 = returnFunc(ctx, article)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockArticleStore_CreateArticle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateArticle'
type MockArticleStore_CreateArticle_Call struct {
	*mock.Call
}

// CreateArticle is a helper method to define mock.On call
//   - ctx context.Context
//   - article *store.Article
func (_e *MockArticleStore_Expecter) CreateArticle(ctx interface{}, article interface{}) *MockArticleStore_CreateArticle_Call {
	return &MockArticleStore_CreateArticle_Call{Call: _e.mock.On("CreateArticle", ctx, article)}
}

func (_c *MockArticleStore_CreateArticle_Call) Run(run func(ctx context.Context, article *store.Article)) *MockArticleStore_CreateArticle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *store.Article
		if args[1] != nil {
			arg1 = args[1].(*store.Article)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockArticleStore_CreateArticle_Call) Return(err error) *MockArticleStore_CreateArticle_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockArticleStore_CreateArticle_Call) RunAndReturn(run func(ctx context.Context, article *store.Article) error) *MockArticleStore_CreateArticle_Call {
	_c.Call.Return(run)
	return _c
}

// GetArticleBySlug provides a mock function for the type MockArticleStore
func (_mock *MockArticleStore) GetArticleBySlug(ctx context.Context, slug string) (*store.ArticleDetails, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetArticleBySlug")
	}

	var r0 *store.ArticleDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*store.ArticleDetails, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *store.ArticleDetails); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.ArticleDetails)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockArticleStore_GetArticleBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetArticleBySlug'
type MockArticleStore_GetArticleBySlug_Call struct {
	*mock.Call
}

// GetArticleBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockArticleStore_Expecter) GetArticleBySlug(ctx interface{}, slug interface{}) *MockArticleStore_GetArticleBySlug_Call {
	return &MockArticleStore_GetArticleBySlug_Call{Call: _e.mock.On("GetArticleBySlug", ctx, slug)}
}

func (_c *MockArticleStore_GetArticleBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockArticleStore_GetArticleBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockArticleStore_GetArticleBySlug_Call) Return(articleDetails *store.ArticleDetails, err error) *MockArticleStore_GetArticleBySlug_Call {
	_c.Call.Return(articleDetails, err)
	return _c
}

func (_c *MockArticleStore_GetArticleBySlug_Call) RunAndReturn(run func(ctx context.Context, slug string) (*store.ArticleDetails, error)) *MockArticleStore_GetArticleBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// ListArticlesPreviews provides a mock function for the type MockArticleStore
func (_mock *MockArticleStore) ListArticlesPreviews(ctx context.Context) ([]store.ArticlePreview, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListArticlesPreviews")
	}

	var r0 []store.ArticlePreview
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]store.ArticlePreview, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []store.ArticlePreview); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.ArticlePreview)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockArticleStore_ListArticlesPreviews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListArticlesPreviews'
type MockArticleStore_ListArticlesPreviews_Call struct {
	*mock.Call
}

// ListArticlesPreviews is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockArticleStore_Expecter) ListArticlesPreviews(ctx interface{}) *MockArticleStore_ListArticlesPreviews_Call {
	return &MockArticleStore_ListArticlesPreviews_Call{Call: _e.mock.On("ListArticlesPreviews", ctx)}
}

func (_c *MockArticleStore_ListArticlesPreviews_Call) Run(run func(ctx context.Context)) *MockArticleStore_ListArticlesPreviews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockArticleStore_ListArticlesPreviews_Call) Return(articlePreviews []store.ArticlePreview, err error) *MockArticleStore_ListArticlesPreviews_Call {
	_c.Call.Return(articlePreviews, err)
	return _c
}

func (_c *MockArticleStore_ListArticlesPreviews_Call) RunAndReturn(run func(ctx context.Context) ([]store.ArticlePreview, error)) *MockArticleStore_ListArticlesPreviews_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthStore creates a new instance of MockAuthStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthStore {
	mock := &MockAuthStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthStore is an autogenerated mock type for the AuthStore type
type MockAuthStore struct {
	mock.Mock
}

type MockAuthStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthStore) EXPECT() *MockAuthStore_Expecter {
	return &MockAuthStore_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockAuthStore
func (_mock *MockAuthStore) CreateUser(ctx context.Context, params store.CreateUserParams) (*store.User, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *store.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, store.CreateUserParams) (*store.User, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, store.CreateUserParams) *store.User); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, store.CreateUserParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthStore_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockAuthStore_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - params store.CreateUserParams
func (_e *MockAuthStore_Expecter) CreateUser(ctx interface{}, params interface{}) *MockAuthStore_CreateUser_Call {
	return &MockAuthStore_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, params)}
}

func (_c *MockAuthStore_CreateUser_Call) Run(run func(ctx context.Context, params store.CreateUserParams)) *MockAuthStore_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 store.CreateUserParams
		if args[1] != nil {
			arg1 = args[1].(store.CreateUserParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthStore_CreateUser_Call) Return(user *store.User, err error) *MockAuthStore_CreateUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthStore_CreateUser_Call) RunAndReturn(run func(ctx context.Context, params store.CreateUserParams) (*store.User, error)) *MockAuthStore_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type MockAuthStore
func (_mock *MockAuthStore) GetUser(ctx context.Context, emailOrUsername string) (*store.User, error) {
	ret := _mock.Called(ctx, emailOrUsername)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *store.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*store.User, error)); ok {
		return returnFunc(ctx, emailOrUsername)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *store.User); ok {
		r0 = returnFunc(ctx, emailOrUsername)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, emailOrUsername)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthStore_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockAuthStore_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - emailOrUsername string
func (_e *MockAuthStore_Expecter) GetUser(ctx interface{}, emailOrUsername interface{}) *MockAuthStore_GetUser_Call {
	return &MockAuthStore_GetUser_Call{Call: _e.mock.On("GetUser", ctx, emailOrUsername)}
}

func (_c *MockAuthStore_GetUser_Call) Run(run func(ctx context.Context, emailOrUsername string)) *MockAuthStore_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthStore_GetUser_Call) Return(user *store.User, err error) *MockAuthStore_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthStore_GetUser_Call) RunAndReturn(run func(ctx context.Context, emailOrUsername string) (*store.User, error)) *MockAuthStore_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockAuthStore
func (_mock *MockAuthStore) GetUserByID(ctx context.Context, userID string) (*store.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *store.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*store.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *store.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthStore_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockAuthStore_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAuthStore_Expecter) GetUserByID(ctx interface{}, userID interface{}) *MockAuthStore_GetUserByID_Call {
	return &MockAuthStore_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, userID)}
}

func (_c *MockAuthStore_GetUserByID_Call) Run(run func(ctx context.Context, userID string)) *MockAuthStore_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthStore_GetUserByID_Call) Return(user *store.User, err error) *MockAuthStore_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthStore_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, userID string) (*store.User, error)) *MockAuthStore_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDigitalAuthorStore creates a new instance of MockDigitalAuthorStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDigitalAuthorStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDigitalAuthorStore {
	mock := &MockDigitalAuthorStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDigitalAuthorStore is an autogenerated mock type for the DigitalAuthorStore type
type MockDigitalAuthorStore struct {
	mock.Mock
}

type MockDigitalAuthorStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDigitalAuthorStore) EXPECT() *MockDigitalAuthorStore_Expecter {
	return &MockDigitalAuthorStore_Expecter{mock: &_m.Mock}
}

// ListDigitalAuthors provides a mock function for the type MockDigitalAuthorStore
func (_mock *MockDigitalAuthorStore) ListDigitalAuthors(ctx context.Context) ([]*store.DigitalAuthor, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListDigitalAuthors")
	}

	var r0 []*store.DigitalAuthor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*store.DigitalAuthor, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*store.DigitalAuthor); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*store.DigitalAuthor)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDigitalAuthorStore_ListDigitalAuthors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDigitalAuthors'
type MockDigitalAuthorStore_ListDigitalAuthors_Call struct {
	*mock.Call
}

// ListDigitalAuthors is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDigitalAuthorStore_Expecter) ListDigitalAuthors(ctx interface{}) *MockDigitalAuthorStore_ListDigitalAuthors_Call {
	return &MockDigitalAuthorStore_ListDigitalAuthors_Call{Call: _e.mock.On("ListDigitalAuthors", ctx)}
}

func (_c *MockDigitalAuthorStore_ListDigitalAuthors_Call) Run(run func(ctx context.Context)) *MockDigitalAuthorStore_ListDigitalAuthors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDigitalAuthorStore_ListDigitalAuthors_Call) Return(digitalAuthors []*store.DigitalAuthor, err error) *MockDigitalAuthorStore_ListDigitalAuthors_Call {
	_c.Call.Return(digitalAuthors, err)
	return _c
}

func (_c *MockDigitalAuthorStore_ListDigitalAuthors_Call) RunAndReturn(run func(ctx context.Context) ([]*store.DigitalAuthor, error)) *MockDigitalAuthorStore_ListDigitalAuthors_Call {
	_c.Call.Return(run)
	return _c
}
