// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateArticle provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateArticle(ctx context.Context, article *Article) error {
	ret := _mock.Called(ctx, article)

	if len(ret) == 0 {
		panic("no return value specified for CreateArticle")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Article) error); ok {
		r0 = returnFunc(ctx, article)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_CreateArticle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateArticle'
type MockRepository_CreateArticle_Call struct {
	*mock.Call
}

// CreateArticle is a helper method to define mock.On call
//   - ctx context.Context
//   - article *Article
func (_e *MockRepository_Expecter) CreateArticle(ctx interface{}, article interface{}) *MockRepository_CreateArticle_Call {
	return &MockRepository_CreateArticle_Call{Call: _e.mock.On("CreateArticle", ctx, article)}
}

func (_c *MockRepository_CreateArticle_Call) Run(run func(ctx context.Context, article *Article)) *MockRepository_CreateArticle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Article
		if args[1] != nil {
			arg1 = args[1].(*Article)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateArticle_Call) Return(err error) *MockRepository_CreateArticle_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_CreateArticle_Call) RunAndReturn(run func(ctx context.Context, article *Article) error) *MockRepository_CreateArticle_Call {
	_c.Call.Return(run)
	return _c
}

// CreateLLMAPIKey provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateLLMAPIKey(ctx context.Context, apiKey CreateLLMAPIKeyParams) (*OpenRouterAPIKey, error) {
	ret := _mock.Called(ctx, apiKey)

	if len(ret) == 0 {
		panic("no return value specified for CreateLLMAPIKey")
	}

	var r0 *OpenRouterAPIKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateLLMAPIKeyParams) (*OpenRouterAPIKey, error)); ok {
		return returnFunc(ctx, apiKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateLLMAPIKeyParams) *OpenRouterAPIKey); ok {
		r0 = returnFunc(ctx, apiKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*OpenRouterAPIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, CreateLLMAPIKeyParams) error); ok {
		r1 = returnFunc(ctx, apiKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CreateLLMAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLLMAPIKey'
type MockRepository_CreateLLMAPIKey_Call struct {
	*mock.Call
}

// CreateLLMAPIKey is a helper method to define mock.On call
//   - ctx context.Context
//   - apiKey CreateLLMAPIKeyParams
func (_e *MockRepository_Expecter) CreateLLMAPIKey(ctx interface{}, apiKey interface{}) *MockRepository_CreateLLMAPIKey_Call {
	return &MockRepository_CreateLLMAPIKey_Call{Call: _e.mock.On("CreateLLMAPIKey", ctx, apiKey)}
}

func (_c *MockRepository_CreateLLMAPIKey_Call) Run(run func(ctx context.Context, apiKey CreateLLMAPIKeyParams)) *MockRepository_CreateLLMAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 CreateLLMAPIKeyParams
		if args[1] != nil {
			arg1 = args[1].(CreateLLMAPIKeyParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateLLMAPIKey_Call) Return(openRouterAPIKey *OpenRouterAPIKey, err error) *MockRepository_CreateLLMAPIKey_Call {
	_c.Call.Return(openRouterAPIKey, err)
	return _c
}

func (_c *MockRepository_CreateLLMAPIKey_Call) RunAndReturn(run func(ctx context.Context, apiKey CreateLLMAPIKeyParams) (*OpenRouterAPIKey, error)) *MockRepository_CreateLLMAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateUser(ctx context.Context, params CreateUserParams) (*User, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateUserParams) (*User, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateUserParams) *User); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, CreateUserParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - params CreateUserParams
func (_e *MockRepository_Expecter) CreateUser(ctx interface{}, params interface{}) *MockRepository_CreateUser_Call {
	return &MockRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, params)}
}

func (_c *MockRepository_CreateUser_Call) Run(run func(ctx context.Context, params CreateUserParams)) *MockRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 CreateUserParams
		if args[1] != nil {
			arg1 = args[1].(CreateUserParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateUser_Call) Return(user *User, err error) *MockRepository_CreateUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_CreateUser_Call) RunAndReturn(run func(ctx context.Context, params CreateUserParams) (*User, error)) *MockRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetArticleBySlug provides a mock function for the type MockRepository
func (_mock *MockRepository) GetArticleBySlug(ctx context.Context, slug string) (*ArticleDetails, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetArticleBySlug")
	}

	var r0 *ArticleDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ArticleDetails, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ArticleDetails); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ArticleDetails)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetArticleBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetArticleBySlug'
type MockRepository_GetArticleBySlug_Call struct {
	*mock.Call
}

// GetArticleBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockRepository_Expecter) GetArticleBySlug(ctx interface{}, slug interface{}) *MockRepository_GetArticleBySlug_Call {
	return &MockRepository_GetArticleBySlug_Call{Call: _e.mock.On("GetArticleBySlug", ctx, slug)}
}

func (_c *MockRepository_GetArticleBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockRepository_GetArticleBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetArticleBySlug_Call) Return(articleDetails *ArticleDetails, err error) *MockRepository_GetArticleBySlug_Call {
	_c.Call.Return(articleDetails, err)
	return _c
}

func (_c *MockRepository_GetArticleBySlug_Call) RunAndReturn(run func(ctx context.Context, slug string) (*ArticleDetails, error)) *MockRepository_GetArticleBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type MockRepository
func (_mock *MockRepository) GetUser(ctx context.Context, emailOrUsername string) (*User, error) {
	ret := _mock.Called(ctx, emailOrUsername)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*User, error)); ok {
		return returnFunc(ctx, emailOrUsername)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *User); ok {
		r0 = returnFunc(ctx, emailOrUsername)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, emailOrUsername)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockRepository_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - emailOrUsername string
func (_e *MockRepository_Expecter) GetUser(ctx interface{}, emailOrUsername interface{}) *MockRepository_GetUser_Call {
	return &MockRepository_GetUser_Call{Call: _e.mock.On("GetUser", ctx, emailOrUsername)}
}

func (_c *MockRepository_GetUser_Call) Run(run func(ctx context.Context, emailOrUsername string)) *MockRepository_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetUser_Call) Return(user *User, err error) *MockRepository_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_GetUser_Call) RunAndReturn(run func(ctx context.Context, emailOrUsername string) (*User, error)) *MockRepository_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetUserByID(ctx context.Context, userID string) (*User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockRepository_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepository_Expecter) GetUserByID(ctx interface{}, userID interface{}) *MockRepository_GetUserByID_Call {
	return &MockRepository_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, userID)}
}

func (_c *MockRepository_GetUserByID_Call) Run(run func(ctx context.Context, userID string)) *MockRepository_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetUserByID_Call) Return(user *User, err error) *MockRepository_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, userID string) (*User, error)) *MockRepository_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListArticlesPreviews provides a mock function for the type MockRepository
func (_mock *MockRepository) ListArticlesPreviews(ctx context.Context, pageSize int, opts ...ListArticlesPreviewsOption) ([]ArticlePreview, string, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, pageSize, opts)
	} else {
		tmpRet = _mock.Called(ctx, pageSize)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListArticlesPreviews")
	}

	var r0 []ArticlePreview
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, ...ListArticlesPreviewsOption) ([]ArticlePreview, string, error)); ok {
		return returnFunc(ctx, pageSize, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, ...ListArticlesPreviewsOption) []ArticlePreview); ok {
		r0 = returnFunc(ctx, pageSize, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ArticlePreview)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, ...ListArticlesPreviewsOption) string); ok {
		r1 = returnFunc(ctx, pageSize, opts...)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int, ...ListArticlesPreviewsOption) error); ok {
		r2 = returnFunc(ctx, pageSize, opts...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_ListArticlesPreviews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListArticlesPreviews'
type MockRepository_ListArticlesPreviews_Call struct {
	*mock.Call
}

// ListArticlesPreviews is a helper method to define mock.On call
//   - ctx context.Context
//   - pageSize int
//   - opts ...ListArticlesPreviewsOption
func (_e *MockRepository_Expecter) ListArticlesPreviews(ctx interface{}, pageSize interface{}, opts ...interface{}) *MockRepository_ListArticlesPreviews_Call {
	return &MockRepository_ListArticlesPreviews_Call{Call: _e.mock.On("ListArticlesPreviews",
		append([]interface{}{ctx, pageSize}, opts...)...)}
}

func (_c *MockRepository_ListArticlesPreviews_Call) Run(run func(ctx context.Context, pageSize int, opts ...ListArticlesPreviewsOption)) *MockRepository_ListArticlesPreviews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []ListArticlesPreviewsOption
		var variadicArgs []ListArticlesPreviewsOption
		if len(args) > 2 {
			variadicArgs = args[2].([]ListArticlesPreviewsOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRepository_ListArticlesPreviews_Call) Return(results []ArticlePreview, nextPageToken string, err error) *MockRepository_ListArticlesPreviews_Call {
	_c.Call.Return(results, nextPageToken, err)
	return _c
}

func (_c *MockRepository_ListArticlesPreviews_Call) RunAndReturn(run func(ctx context.Context, pageSize int, opts ...ListArticlesPreviewsOption) ([]ArticlePreview, string, error)) *MockRepository_ListArticlesPreviews_Call {
	_c.Call.Return(run)
	return _c
}

// ListDigitalAuthorsWithArticleSlugs provides a mock function for the type MockRepository
func (_mock *MockRepository) ListDigitalAuthorsWithArticleSlugs(ctx context.Context) ([]*DigitalAuthorWithArticleSlugs, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListDigitalAuthorsWithArticleSlugs")
	}

	var r0 []*DigitalAuthorWithArticleSlugs
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*DigitalAuthorWithArticleSlugs, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*DigitalAuthorWithArticleSlugs); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*DigitalAuthorWithArticleSlugs)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListDigitalAuthorsWithArticleSlugs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDigitalAuthorsWithArticleSlugs'
type MockRepository_ListDigitalAuthorsWithArticleSlugs_Call struct {
	*mock.Call
}

// ListDigitalAuthorsWithArticleSlugs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) ListDigitalAuthorsWithArticleSlugs(ctx interface{}) *MockRepository_ListDigitalAuthorsWithArticleSlugs_Call {
	return &MockRepository_ListDigitalAuthorsWithArticleSlugs_Call{Call: _e.mock.On("ListDigitalAuthorsWithArticleSlugs", ctx)}
}

func (_c *MockRepository_ListDigitalAuthorsWithArticleSlugs_Call) Run(run func(ctx context.Context)) *MockRepository_ListDigitalAuthorsWithArticleSlugs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_ListDigitalAuthorsWithArticleSlugs_Call) Return(digitalAuthorWithArticleSlugss []*DigitalAuthorWithArticleSlugs, err error) *MockRepository_ListDigitalAuthorsWithArticleSlugs_Call {
	_c.Call.Return(digitalAuthorWithArticleSlugss, err)
	return _c
}

func (_c *MockRepository_ListDigitalAuthorsWithArticleSlugs_Call) RunAndReturn(run func(ctx context.Context) ([]*DigitalAuthorWithArticleSlugs, error)) *MockRepository_ListDigitalAuthorsWithArticleSlugs_Call {
	_c.Call.Return(run)
	return _c
}

// ListLLMAPIKeysByUserID provides a mock function for the type MockRepository
func (_mock *MockRepository) ListLLMAPIKeysByUserID(ctx context.Context, userID string) ([]*OpenRouterAPIKey, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListLLMAPIKeysByUserID")
	}

	var r0 []*OpenRouterAPIKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*OpenRouterAPIKey, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*OpenRouterAPIKey); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*OpenRouterAPIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListLLMAPIKeysByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListLLMAPIKeysByUserID'
type MockRepository_ListLLMAPIKeysByUserID_Call struct {
	*mock.Call
}

// ListLLMAPIKeysByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepository_Expecter) ListLLMAPIKeysByUserID(ctx interface{}, userID interface{}) *MockRepository_ListLLMAPIKeysByUserID_Call {
	return &MockRepository_ListLLMAPIKeysByUserID_Call{Call: _e.mock.On("ListLLMAPIKeysByUserID", ctx, userID)}
}

func (_c *MockRepository_ListLLMAPIKeysByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockRepository_ListLLMAPIKeysByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ListLLMAPIKeysByUserID_Call) Return(openRouterAPIKeys []*OpenRouterAPIKey, err error) *MockRepository_ListLLMAPIKeysByUserID_Call {
	_c.Call.Return(openRouterAPIKeys, err)
	return _c
}

func (_c *MockRepository_ListLLMAPIKeysByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*OpenRouterAPIKey, error)) *MockRepository_ListLLMAPIKeysByUserID_Call {
	_c.Call.Return(run)
	return _c
}
