// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tuananhlai/brevity-go/internal/model"
)

// NewMockArticleRepository creates a new instance of MockArticleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockArticleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockArticleRepository {
	mock := &MockArticleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockArticleRepository is an autogenerated mock type for the ArticleRepository type
type MockArticleRepository struct {
	mock.Mock
}

type MockArticleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockArticleRepository) EXPECT() *MockArticleRepository_Expecter {
	return &MockArticleRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockArticleRepository
func (_mock *MockArticleRepository) Create(ctx context.Context, article *model.Article) error {
	ret := _mock.Called(ctx, article)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Article) error); ok {
		r0 = returnFunc(ctx, article)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockArticleRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockArticleRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx
//   - article
func (_e *MockArticleRepository_Expecter) Create(ctx interface{}, article interface{}) *MockArticleRepository_Create_Call {
	return &MockArticleRepository_Create_Call{Call: _e.mock.On("Create", ctx, article)}
}

func (_c *MockArticleRepository_Create_Call) Run(run func(ctx context.Context, article *model.Article)) *MockArticleRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Article))
	})
	return _c
}

func (_c *MockArticleRepository_Create_Call) Return(err error) *MockArticleRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockArticleRepository_Create_Call) RunAndReturn(run func(ctx context.Context, article *model.Article) error) *MockArticleRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetBySlug provides a mock function for the type MockArticleRepository
func (_mock *MockArticleRepository) GetBySlug(ctx context.Context, slug string) (*model.ArticleDetails, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetBySlug")
	}

	var r0 *model.ArticleDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.ArticleDetails, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.ArticleDetails); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ArticleDetails)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockArticleRepository_GetBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySlug'
type MockArticleRepository_GetBySlug_Call struct {
	*mock.Call
}

// GetBySlug is a helper method to define mock.On call
//   - ctx
//   - slug
func (_e *MockArticleRepository_Expecter) GetBySlug(ctx interface{}, slug interface{}) *MockArticleRepository_GetBySlug_Call {
	return &MockArticleRepository_GetBySlug_Call{Call: _e.mock.On("GetBySlug", ctx, slug)}
}

func (_c *MockArticleRepository_GetBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockArticleRepository_GetBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockArticleRepository_GetBySlug_Call) Return(articleDetails *model.ArticleDetails, err error) *MockArticleRepository_GetBySlug_Call {
	_c.Call.Return(articleDetails, err)
	return _c
}

func (_c *MockArticleRepository_GetBySlug_Call) RunAndReturn(run func(ctx context.Context, slug string) (*model.ArticleDetails, error)) *MockArticleRepository_GetBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// ListPreviews provides a mock function for the type MockArticleRepository
func (_mock *MockArticleRepository) ListPreviews(ctx context.Context, pageSize int, opts ...ListPreviewsOption) ([]model.ArticlePreview, string, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, pageSize, opts)
	} else {
		tmpRet = _mock.Called(ctx, pageSize)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListPreviews")
	}

	var r0 []model.ArticlePreview
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, ...ListPreviewsOption) ([]model.ArticlePreview, string, error)); ok {
		return returnFunc(ctx, pageSize, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, ...ListPreviewsOption) []model.ArticlePreview); ok {
		r0 = returnFunc(ctx, pageSize, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ArticlePreview)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, ...ListPreviewsOption) string); ok {
		r1 = returnFunc(ctx, pageSize, opts...)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int, ...ListPreviewsOption) error); ok {
		r2 = returnFunc(ctx, pageSize, opts...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockArticleRepository_ListPreviews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPreviews'
type MockArticleRepository_ListPreviews_Call struct {
	*mock.Call
}

// ListPreviews is a helper method to define mock.On call
//   - ctx
//   - pageSize
//   - opts
func (_e *MockArticleRepository_Expecter) ListPreviews(ctx interface{}, pageSize interface{}, opts ...interface{}) *MockArticleRepository_ListPreviews_Call {
	return &MockArticleRepository_ListPreviews_Call{Call: _e.mock.On("ListPreviews",
		append([]interface{}{ctx, pageSize}, opts...)...)}
}

func (_c *MockArticleRepository_ListPreviews_Call) Run(run func(ctx context.Context, pageSize int, opts ...ListPreviewsOption)) *MockArticleRepository_ListPreviews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]ListPreviewsOption)
		run(args[0].(context.Context), args[1].(int), variadicArgs...)
	})
	return _c
}

func (_c *MockArticleRepository_ListPreviews_Call) Return(results []model.ArticlePreview, nextPageToken string, err error) *MockArticleRepository_ListPreviews_Call {
	_c.Call.Return(results, nextPageToken, err)
	return _c
}

func (_c *MockArticleRepository_ListPreviews_Call) RunAndReturn(run func(ctx context.Context, pageSize int, opts ...ListPreviewsOption) ([]model.ArticlePreview, string, error)) *MockArticleRepository_ListPreviews_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthRepository creates a new instance of MockAuthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthRepository {
	mock := &MockAuthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthRepository is an autogenerated mock type for the AuthRepository type
type MockAuthRepository struct {
	mock.Mock
}

type MockAuthRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthRepository) EXPECT() *MockAuthRepository_Expecter {
	return &MockAuthRepository_Expecter{mock: &_m.Mock}
}

// CreateRefreshToken provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) CreateRefreshToken(ctx context.Context, params CreateRefreshTokenParams) (*model.RefreshToken, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateRefreshToken")
	}

	var r0 *model.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateRefreshTokenParams) (*model.RefreshToken, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateRefreshTokenParams) *model.RefreshToken); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.RefreshToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, CreateRefreshTokenParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepository_CreateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRefreshToken'
type MockAuthRepository_CreateRefreshToken_Call struct {
	*mock.Call
}

// CreateRefreshToken is a helper method to define mock.On call
//   - ctx
//   - params
func (_e *MockAuthRepository_Expecter) CreateRefreshToken(ctx interface{}, params interface{}) *MockAuthRepository_CreateRefreshToken_Call {
	return &MockAuthRepository_CreateRefreshToken_Call{Call: _e.mock.On("CreateRefreshToken", ctx, params)}
}

func (_c *MockAuthRepository_CreateRefreshToken_Call) Run(run func(ctx context.Context, params CreateRefreshTokenParams)) *MockAuthRepository_CreateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(CreateRefreshTokenParams))
	})
	return _c
}

func (_c *MockAuthRepository_CreateRefreshToken_Call) Return(refreshToken *model.RefreshToken, err error) *MockAuthRepository_CreateRefreshToken_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *MockAuthRepository_CreateRefreshToken_Call) RunAndReturn(run func(ctx context.Context, params CreateRefreshTokenParams) (*model.RefreshToken, error)) *MockAuthRepository_CreateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) CreateUser(ctx context.Context, params CreateUserParams) (*model.AuthUser, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *model.AuthUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateUserParams) (*model.AuthUser, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateUserParams) *model.AuthUser); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AuthUser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, CreateUserParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockAuthRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx
//   - params
func (_e *MockAuthRepository_Expecter) CreateUser(ctx interface{}, params interface{}) *MockAuthRepository_CreateUser_Call {
	return &MockAuthRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, params)}
}

func (_c *MockAuthRepository_CreateUser_Call) Run(run func(ctx context.Context, params CreateUserParams)) *MockAuthRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(CreateUserParams))
	})
	return _c
}

func (_c *MockAuthRepository_CreateUser_Call) Return(authUser *model.AuthUser, err error) *MockAuthRepository_CreateUser_Call {
	_c.Call.Return(authUser, err)
	return _c
}

func (_c *MockAuthRepository_CreateUser_Call) RunAndReturn(run func(ctx context.Context, params CreateUserParams) (*model.AuthUser, error)) *MockAuthRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetRefreshToken provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) GetRefreshToken(ctx context.Context, token string) (*model.RefreshToken, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshToken")
	}

	var r0 *model.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.RefreshToken, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.RefreshToken); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.RefreshToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepository_GetRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefreshToken'
type MockAuthRepository_GetRefreshToken_Call struct {
	*mock.Call
}

// GetRefreshToken is a helper method to define mock.On call
//   - ctx
//   - token
func (_e *MockAuthRepository_Expecter) GetRefreshToken(ctx interface{}, token interface{}) *MockAuthRepository_GetRefreshToken_Call {
	return &MockAuthRepository_GetRefreshToken_Call{Call: _e.mock.On("GetRefreshToken", ctx, token)}
}

func (_c *MockAuthRepository_GetRefreshToken_Call) Run(run func(ctx context.Context, token string)) *MockAuthRepository_GetRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthRepository_GetRefreshToken_Call) Return(refreshToken *model.RefreshToken, err error) *MockAuthRepository_GetRefreshToken_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *MockAuthRepository_GetRefreshToken_Call) RunAndReturn(run func(ctx context.Context, token string) (*model.RefreshToken, error)) *MockAuthRepository_GetRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) GetUser(ctx context.Context, emailOrUsername string) (*model.AuthUser, error) {
	ret := _mock.Called(ctx, emailOrUsername)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *model.AuthUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.AuthUser, error)); ok {
		return returnFunc(ctx, emailOrUsername)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.AuthUser); ok {
		r0 = returnFunc(ctx, emailOrUsername)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AuthUser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, emailOrUsername)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepository_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockAuthRepository_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx
//   - emailOrUsername
func (_e *MockAuthRepository_Expecter) GetUser(ctx interface{}, emailOrUsername interface{}) *MockAuthRepository_GetUser_Call {
	return &MockAuthRepository_GetUser_Call{Call: _e.mock.On("GetUser", ctx, emailOrUsername)}
}

func (_c *MockAuthRepository_GetUser_Call) Run(run func(ctx context.Context, emailOrUsername string)) *MockAuthRepository_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthRepository_GetUser_Call) Return(authUser *model.AuthUser, err error) *MockAuthRepository_GetUser_Call {
	_c.Call.Return(authUser, err)
	return _c
}

func (_c *MockAuthRepository_GetUser_Call) RunAndReturn(run func(ctx context.Context, emailOrUsername string) (*model.AuthUser, error)) *MockAuthRepository_GetUser_Call {
	_c.Call.Return(run)
	return _c
}
