package repository

import (
	"encoding/base64"
	"encoding/json"
)

// generatePageToken creates a page token from the given value. The value must be JSON-serializable.
func generatePageToken(v interface{}) (string, error) {
	json, err := json.Marshal(v)
	if err != nil {
		return "", err
	}

	return base64.StdEncoding.EncodeToString(json), nil
}

// parsePageToken parses a page token into the given variable. The token must be generated by generatePageToken.
//
// example:
//
//	var v ListPreviewsPageToken{}
//	err := parsePageToken(token, &v)
//	if err != nil {
//		return err
//	}
func parsePageToken(token string, v interface{}) error {
	jsonString, err := base64.StdEncoding.DecodeString(token)
	if err != nil {
		return err
	}

	return json.Unmarshal(jsonString, v)
}
