services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/go:1.25-bookworm
    command: sleep infinity
    volumes:
      - .:/workspaces/brevity-go:cached
      # Homebrew caches
      - brew-download-cache:/home/linuxbrew/.cache/Homebrew

volumes:
  brew-download-cache: