// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package llmapikey

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tuananhlai/brevity-go/internal/store"
)

// NewMockCrypter creates a new instance of MockCrypter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCrypter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCrypter {
	mock := &MockCrypter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCrypter is an autogenerated mock type for the Crypter type
type MockCrypter struct {
	mock.Mock
}

type MockCrypter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCrypter) EXPECT() *MockCrypter_Expecter {
	return &MockCrypter_Expecter{mock: &_m.Mock}
}

// Decrypt provides a mock function for the type MockCrypter
func (_mock *MockCrypter) Decrypt(cipherText []byte) ([]byte, error) {
	ret := _mock.Called(cipherText)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) ([]byte, error)); ok {
		return returnFunc(cipherText)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = returnFunc(cipherText)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(cipherText)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCrypter_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type MockCrypter_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - cipherText []byte
func (_e *MockCrypter_Expecter) Decrypt(cipherText interface{}) *MockCrypter_Decrypt_Call {
	return &MockCrypter_Decrypt_Call{Call: _e.mock.On("Decrypt", cipherText)}
}

func (_c *MockCrypter_Decrypt_Call) Run(run func(cipherText []byte)) *MockCrypter_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCrypter_Decrypt_Call) Return(bytes []byte, err error) *MockCrypter_Decrypt_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockCrypter_Decrypt_Call) RunAndReturn(run func(cipherText []byte) ([]byte, error)) *MockCrypter_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// Encrypt provides a mock function for the type MockCrypter
func (_mock *MockCrypter) Encrypt(plainText []byte) []byte {
	ret := _mock.Called(plainText)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 []byte
	if returnFunc, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = returnFunc(plainText)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	return r0
}

// MockCrypter_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type MockCrypter_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - plainText []byte
func (_e *MockCrypter_Expecter) Encrypt(plainText interface{}) *MockCrypter_Encrypt_Call {
	return &MockCrypter_Encrypt_Call{Call: _e.mock.On("Encrypt", plainText)}
}

func (_c *MockCrypter_Encrypt_Call) Run(run func(plainText []byte)) *MockCrypter_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCrypter_Encrypt_Call) Return(bytes []byte) *MockCrypter_Encrypt_Call {
	_c.Call.Return(bytes)
	return _c
}

func (_c *MockCrypter_Encrypt_Call) RunAndReturn(run func(plainText []byte) []byte) *MockCrypter_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLLMApiKeyStore creates a new instance of MockLLMApiKeyStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLLMApiKeyStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLLMApiKeyStore {
	mock := &MockLLMApiKeyStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLLMApiKeyStore is an autogenerated mock type for the LLMApiKeyStore type
type MockLLMApiKeyStore struct {
	mock.Mock
}

type MockLLMApiKeyStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLLMApiKeyStore) EXPECT() *MockLLMApiKeyStore_Expecter {
	return &MockLLMApiKeyStore_Expecter{mock: &_m.Mock}
}

// CreateLLMAPIKey provides a mock function for the type MockLLMApiKeyStore
func (_mock *MockLLMApiKeyStore) CreateLLMAPIKey(ctx context.Context, apiKey store.CreateLLMAPIKeyParams) (*store.OpenRouterAPIKey, error) {
	ret := _mock.Called(ctx, apiKey)

	if len(ret) == 0 {
		panic("no return value specified for CreateLLMAPIKey")
	}

	var r0 *store.OpenRouterAPIKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, store.CreateLLMAPIKeyParams) (*store.OpenRouterAPIKey, error)); ok {
		return returnFunc(ctx, apiKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, store.CreateLLMAPIKeyParams) *store.OpenRouterAPIKey); ok {
		r0 = returnFunc(ctx, apiKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.OpenRouterAPIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, store.CreateLLMAPIKeyParams) error); ok {
		r1 = returnFunc(ctx, apiKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLLMApiKeyStore_CreateLLMAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLLMAPIKey'
type MockLLMApiKeyStore_CreateLLMAPIKey_Call struct {
	*mock.Call
}

// CreateLLMAPIKey is a helper method to define mock.On call
//   - ctx context.Context
//   - apiKey store.CreateLLMAPIKeyParams
func (_e *MockLLMApiKeyStore_Expecter) CreateLLMAPIKey(ctx interface{}, apiKey interface{}) *MockLLMApiKeyStore_CreateLLMAPIKey_Call {
	return &MockLLMApiKeyStore_CreateLLMAPIKey_Call{Call: _e.mock.On("CreateLLMAPIKey", ctx, apiKey)}
}

func (_c *MockLLMApiKeyStore_CreateLLMAPIKey_Call) Run(run func(ctx context.Context, apiKey store.CreateLLMAPIKeyParams)) *MockLLMApiKeyStore_CreateLLMAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 store.CreateLLMAPIKeyParams
		if args[1] != nil {
			arg1 = args[1].(store.CreateLLMAPIKeyParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLLMApiKeyStore_CreateLLMAPIKey_Call) Return(openRouterAPIKey *store.OpenRouterAPIKey, err error) *MockLLMApiKeyStore_CreateLLMAPIKey_Call {
	_c.Call.Return(openRouterAPIKey, err)
	return _c
}

func (_c *MockLLMApiKeyStore_CreateLLMAPIKey_Call) RunAndReturn(run func(ctx context.Context, apiKey store.CreateLLMAPIKeyParams) (*store.OpenRouterAPIKey, error)) *MockLLMApiKeyStore_CreateLLMAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// ListLLMAPIKeysByUserID provides a mock function for the type MockLLMApiKeyStore
func (_mock *MockLLMApiKeyStore) ListLLMAPIKeysByUserID(ctx context.Context, userID string) ([]*store.OpenRouterAPIKey, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListLLMAPIKeysByUserID")
	}

	var r0 []*store.OpenRouterAPIKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*store.OpenRouterAPIKey, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*store.OpenRouterAPIKey); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*store.OpenRouterAPIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLLMApiKeyStore_ListLLMAPIKeysByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListLLMAPIKeysByUserID'
type MockLLMApiKeyStore_ListLLMAPIKeysByUserID_Call struct {
	*mock.Call
}

// ListLLMAPIKeysByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockLLMApiKeyStore_Expecter) ListLLMAPIKeysByUserID(ctx interface{}, userID interface{}) *MockLLMApiKeyStore_ListLLMAPIKeysByUserID_Call {
	return &MockLLMApiKeyStore_ListLLMAPIKeysByUserID_Call{Call: _e.mock.On("ListLLMAPIKeysByUserID", ctx, userID)}
}

func (_c *MockLLMApiKeyStore_ListLLMAPIKeysByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockLLMApiKeyStore_ListLLMAPIKeysByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLLMApiKeyStore_ListLLMAPIKeysByUserID_Call) Return(openRouterAPIKeys []*store.OpenRouterAPIKey, err error) *MockLLMApiKeyStore_ListLLMAPIKeysByUserID_Call {
	_c.Call.Return(openRouterAPIKeys, err)
	return _c
}

func (_c *MockLLMApiKeyStore_ListLLMAPIKeysByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*store.OpenRouterAPIKey, error)) *MockLLMApiKeyStore_ListLLMAPIKeysByUserID_Call {
	_c.Call.Return(run)
	return _c
}
