// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package llmapikey

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, apiKey CreateParams) (*StoredAPIKey, error) {
	ret := _mock.Called(ctx, apiKey)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *StoredAPIKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateParams) (*StoredAPIKey, error)); ok {
		return returnFunc(ctx, apiKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateParams) *StoredAPIKey); ok {
		r0 = returnFunc(ctx, apiKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*StoredAPIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, CreateParams) error); ok {
		r1 = returnFunc(ctx, apiKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - apiKey CreateParams
func (_e *MockRepository_Expecter) Create(ctx interface{}, apiKey interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, apiKey)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, apiKey CreateParams)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 CreateParams
		if args[1] != nil {
			arg1 = args[1].(CreateParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(storedAPIKey *StoredAPIKey, err error) *MockRepository_Create_Call {
	_c.Call.Return(storedAPIKey, err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, apiKey CreateParams) (*StoredAPIKey, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function for the type MockRepository
func (_mock *MockRepository) ListByUserID(ctx context.Context, userID string) ([]*StoredAPIKey, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []*StoredAPIKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*StoredAPIKey, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*StoredAPIKey); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*StoredAPIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type MockRepository_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepository_Expecter) ListByUserID(ctx interface{}, userID interface{}) *MockRepository_ListByUserID_Call {
	return &MockRepository_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userID)}
}

func (_c *MockRepository_ListByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockRepository_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ListByUserID_Call) Return(storedAPIKeys []*StoredAPIKey, err error) *MockRepository_ListByUserID_Call {
	_c.Call.Return(storedAPIKeys, err)
	return _c
}

func (_c *MockRepository_ListByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*StoredAPIKey, error)) *MockRepository_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCrypter creates a new instance of MockCrypter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCrypter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCrypter {
	mock := &MockCrypter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCrypter is an autogenerated mock type for the Crypter type
type MockCrypter struct {
	mock.Mock
}

type MockCrypter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCrypter) EXPECT() *MockCrypter_Expecter {
	return &MockCrypter_Expecter{mock: &_m.Mock}
}

// Decrypt provides a mock function for the type MockCrypter
func (_mock *MockCrypter) Decrypt(cipherText []byte) ([]byte, error) {
	ret := _mock.Called(cipherText)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) ([]byte, error)); ok {
		return returnFunc(cipherText)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = returnFunc(cipherText)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(cipherText)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCrypter_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type MockCrypter_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - cipherText []byte
func (_e *MockCrypter_Expecter) Decrypt(cipherText interface{}) *MockCrypter_Decrypt_Call {
	return &MockCrypter_Decrypt_Call{Call: _e.mock.On("Decrypt", cipherText)}
}

func (_c *MockCrypter_Decrypt_Call) Run(run func(cipherText []byte)) *MockCrypter_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCrypter_Decrypt_Call) Return(bytes []byte, err error) *MockCrypter_Decrypt_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockCrypter_Decrypt_Call) RunAndReturn(run func(cipherText []byte) ([]byte, error)) *MockCrypter_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// Encrypt provides a mock function for the type MockCrypter
func (_mock *MockCrypter) Encrypt(plainText []byte) []byte {
	ret := _mock.Called(plainText)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 []byte
	if returnFunc, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = returnFunc(plainText)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	return r0
}

// MockCrypter_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type MockCrypter_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - plainText []byte
func (_e *MockCrypter_Expecter) Encrypt(plainText interface{}) *MockCrypter_Encrypt_Call {
	return &MockCrypter_Encrypt_Call{Call: _e.mock.On("Encrypt", plainText)}
}

func (_c *MockCrypter_Encrypt_Call) Run(run func(plainText []byte)) *MockCrypter_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCrypter_Encrypt_Call) Return(bytes []byte) *MockCrypter_Encrypt_Call {
	_c.Call.Return(bytes)
	return _c
}

func (_c *MockCrypter_Encrypt_Call) RunAndReturn(run func(plainText []byte) []byte) *MockCrypter_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockService
func (_mock *MockService) Create(ctx context.Context, apiKey CreateInput) (*APIKey, error) {
	ret := _mock.Called(ctx, apiKey)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *APIKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateInput) (*APIKey, error)); ok {
		return returnFunc(ctx, apiKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateInput) *APIKey); ok {
		r0 = returnFunc(ctx, apiKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*APIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, CreateInput) error); ok {
		r1 = returnFunc(ctx, apiKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - apiKey CreateInput
func (_e *MockService_Expecter) Create(ctx interface{}, apiKey interface{}) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", ctx, apiKey)}
}

func (_c *MockService_Create_Call) Run(run func(ctx context.Context, apiKey CreateInput)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 CreateInput
		if args[1] != nil {
			arg1 = args[1].(CreateInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Create_Call) Return(aPIKey *APIKey, err error) *MockService_Create_Call {
	_c.Call.Return(aPIKey, err)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(ctx context.Context, apiKey CreateInput) (*APIKey, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function for the type MockService
func (_mock *MockService) ListByUserID(ctx context.Context, userID string) ([]*APIKey, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []*APIKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*APIKey, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*APIKey); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*APIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type MockService_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockService_Expecter) ListByUserID(ctx interface{}, userID interface{}) *MockService_ListByUserID_Call {
	return &MockService_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userID)}
}

func (_c *MockService_ListByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockService_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_ListByUserID_Call) Return(aPIKeys []*APIKey, err error) *MockService_ListByUserID_Call {
	_c.Call.Return(aPIKeys, err)
	return _c
}

func (_c *MockService_ListByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*APIKey, error)) *MockService_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}
