// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package llmapikey

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockCrypter creates a new instance of MockCrypter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCrypter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCrypter {
	mock := &MockCrypter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCrypter is an autogenerated mock type for the Crypter type
type MockCrypter struct {
	mock.Mock
}

type MockCrypter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCrypter) EXPECT() *MockCrypter_Expecter {
	return &MockCrypter_Expecter{mock: &_m.Mock}
}

// Decrypt provides a mock function for the type MockCrypter
func (_mock *MockCrypter) Decrypt(cipherText []byte) ([]byte, error) {
	ret := _mock.Called(cipherText)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) ([]byte, error)); ok {
		return returnFunc(cipherText)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = returnFunc(cipherText)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(cipherText)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCrypter_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type MockCrypter_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - cipherText []byte
func (_e *MockCrypter_Expecter) Decrypt(cipherText interface{}) *MockCrypter_Decrypt_Call {
	return &MockCrypter_Decrypt_Call{Call: _e.mock.On("Decrypt", cipherText)}
}

func (_c *MockCrypter_Decrypt_Call) Run(run func(cipherText []byte)) *MockCrypter_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCrypter_Decrypt_Call) Return(bytes []byte, err error) *MockCrypter_Decrypt_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockCrypter_Decrypt_Call) RunAndReturn(run func(cipherText []byte) ([]byte, error)) *MockCrypter_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// Encrypt provides a mock function for the type MockCrypter
func (_mock *MockCrypter) Encrypt(plainText []byte) []byte {
	ret := _mock.Called(plainText)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 []byte
	if returnFunc, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = returnFunc(plainText)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	return r0
}

// MockCrypter_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type MockCrypter_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - plainText []byte
func (_e *MockCrypter_Expecter) Encrypt(plainText interface{}) *MockCrypter_Encrypt_Call {
	return &MockCrypter_Encrypt_Call{Call: _e.mock.On("Encrypt", plainText)}
}

func (_c *MockCrypter_Encrypt_Call) Run(run func(plainText []byte)) *MockCrypter_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCrypter_Encrypt_Call) Return(bytes []byte) *MockCrypter_Encrypt_Call {
	_c.Call.Return(bytes)
	return _c
}

func (_c *MockCrypter_Encrypt_Call) RunAndReturn(run func(plainText []byte) []byte) *MockCrypter_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}
