// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package articles

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tuananhlai/brevity-go/internal/repository"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockService
func (_mock *MockService) Create(ctx context.Context, article *repository.Article) error {
	ret := _mock.Called(ctx, article)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repository.Article) error); ok {
		r0 = returnFunc(ctx, article)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - article *repository.Article
func (_e *MockService_Expecter) Create(ctx interface{}, article interface{}) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", ctx, article)}
}

func (_c *MockService_Create_Call) Run(run func(ctx context.Context, article *repository.Article)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *repository.Article
		if args[1] != nil {
			arg1 = args[1].(*repository.Article)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Create_Call) Return(err error) *MockService_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(ctx context.Context, article *repository.Article) error) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetBySlug provides a mock function for the type MockService
func (_mock *MockService) GetBySlug(ctx context.Context, slug string) (*repository.ArticleDetails, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetBySlug")
	}

	var r0 *repository.ArticleDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*repository.ArticleDetails, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *repository.ArticleDetails); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.ArticleDetails)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySlug'
type MockService_GetBySlug_Call struct {
	*mock.Call
}

// GetBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockService_Expecter) GetBySlug(ctx interface{}, slug interface{}) *MockService_GetBySlug_Call {
	return &MockService_GetBySlug_Call{Call: _e.mock.On("GetBySlug", ctx, slug)}
}

func (_c *MockService_GetBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockService_GetBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetBySlug_Call) Return(articleDetails *repository.ArticleDetails, err error) *MockService_GetBySlug_Call {
	_c.Call.Return(articleDetails, err)
	return _c
}

func (_c *MockService_GetBySlug_Call) RunAndReturn(run func(ctx context.Context, slug string) (*repository.ArticleDetails, error)) *MockService_GetBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// ListPreviews provides a mock function for the type MockService
func (_mock *MockService) ListPreviews(ctx context.Context) ([]repository.ArticlePreview, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPreviews")
	}

	var r0 []repository.ArticlePreview
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]repository.ArticlePreview, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []repository.ArticlePreview); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.ArticlePreview)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListPreviews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPreviews'
type MockService_ListPreviews_Call struct {
	*mock.Call
}

// ListPreviews is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) ListPreviews(ctx interface{}) *MockService_ListPreviews_Call {
	return &MockService_ListPreviews_Call{Call: _e.mock.On("ListPreviews", ctx)}
}

func (_c *MockService_ListPreviews_Call) Run(run func(ctx context.Context)) *MockService_ListPreviews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_ListPreviews_Call) Return(articlePreviews []repository.ArticlePreview, err error) *MockService_ListPreviews_Call {
	_c.Call.Return(articlePreviews, err)
	return _c
}

func (_c *MockService_ListPreviews_Call) RunAndReturn(run func(ctx context.Context) ([]repository.ArticlePreview, error)) *MockService_ListPreviews_Call {
	_c.Call.Return(run)
	return _c
}
