// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package articles

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, article *Article) error {
	ret := _mock.Called(ctx, article)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Article) error); ok {
		r0 = returnFunc(ctx, article)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - article *Article
func (_e *MockRepository_Expecter) Create(ctx interface{}, article interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, article)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, article *Article)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Article
		if args[1] != nil {
			arg1 = args[1].(*Article)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(err error) *MockRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, article *Article) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetBySlug provides a mock function for the type MockRepository
func (_mock *MockRepository) GetBySlug(ctx context.Context, slug string) (*ArticleDetails, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetBySlug")
	}

	var r0 *ArticleDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ArticleDetails, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ArticleDetails); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ArticleDetails)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySlug'
type MockRepository_GetBySlug_Call struct {
	*mock.Call
}

// GetBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockRepository_Expecter) GetBySlug(ctx interface{}, slug interface{}) *MockRepository_GetBySlug_Call {
	return &MockRepository_GetBySlug_Call{Call: _e.mock.On("GetBySlug", ctx, slug)}
}

func (_c *MockRepository_GetBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockRepository_GetBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetBySlug_Call) Return(articleDetails *ArticleDetails, err error) *MockRepository_GetBySlug_Call {
	_c.Call.Return(articleDetails, err)
	return _c
}

func (_c *MockRepository_GetBySlug_Call) RunAndReturn(run func(ctx context.Context, slug string) (*ArticleDetails, error)) *MockRepository_GetBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// ListPreviews provides a mock function for the type MockRepository
func (_mock *MockRepository) ListPreviews(ctx context.Context, pageSize int, opts ...ListPreviewsOption) ([]ArticlePreview, string, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, pageSize, opts)
	} else {
		tmpRet = _mock.Called(ctx, pageSize)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListPreviews")
	}

	var r0 []ArticlePreview
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, ...ListPreviewsOption) ([]ArticlePreview, string, error)); ok {
		return returnFunc(ctx, pageSize, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, ...ListPreviewsOption) []ArticlePreview); ok {
		r0 = returnFunc(ctx, pageSize, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ArticlePreview)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, ...ListPreviewsOption) string); ok {
		r1 = returnFunc(ctx, pageSize, opts...)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int, ...ListPreviewsOption) error); ok {
		r2 = returnFunc(ctx, pageSize, opts...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_ListPreviews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPreviews'
type MockRepository_ListPreviews_Call struct {
	*mock.Call
}

// ListPreviews is a helper method to define mock.On call
//   - ctx context.Context
//   - pageSize int
//   - opts ...ListPreviewsOption
func (_e *MockRepository_Expecter) ListPreviews(ctx interface{}, pageSize interface{}, opts ...interface{}) *MockRepository_ListPreviews_Call {
	return &MockRepository_ListPreviews_Call{Call: _e.mock.On("ListPreviews",
		append([]interface{}{ctx, pageSize}, opts...)...)}
}

func (_c *MockRepository_ListPreviews_Call) Run(run func(ctx context.Context, pageSize int, opts ...ListPreviewsOption)) *MockRepository_ListPreviews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []ListPreviewsOption
		var variadicArgs []ListPreviewsOption
		if len(args) > 2 {
			variadicArgs = args[2].([]ListPreviewsOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRepository_ListPreviews_Call) Return(results []ArticlePreview, nextPageToken string, err error) *MockRepository_ListPreviews_Call {
	_c.Call.Return(results, nextPageToken, err)
	return _c
}

func (_c *MockRepository_ListPreviews_Call) RunAndReturn(run func(ctx context.Context, pageSize int, opts ...ListPreviewsOption) ([]ArticlePreview, string, error)) *MockRepository_ListPreviews_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockService
func (_mock *MockService) Create(ctx context.Context, article *Article) error {
	ret := _mock.Called(ctx, article)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Article) error); ok {
		r0 = returnFunc(ctx, article)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - article *Article
func (_e *MockService_Expecter) Create(ctx interface{}, article interface{}) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", ctx, article)}
}

func (_c *MockService_Create_Call) Run(run func(ctx context.Context, article *Article)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Article
		if args[1] != nil {
			arg1 = args[1].(*Article)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Create_Call) Return(err error) *MockService_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(ctx context.Context, article *Article) error) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetBySlug provides a mock function for the type MockService
func (_mock *MockService) GetBySlug(ctx context.Context, slug string) (*ArticleDetails, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetBySlug")
	}

	var r0 *ArticleDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ArticleDetails, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ArticleDetails); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ArticleDetails)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySlug'
type MockService_GetBySlug_Call struct {
	*mock.Call
}

// GetBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockService_Expecter) GetBySlug(ctx interface{}, slug interface{}) *MockService_GetBySlug_Call {
	return &MockService_GetBySlug_Call{Call: _e.mock.On("GetBySlug", ctx, slug)}
}

func (_c *MockService_GetBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockService_GetBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetBySlug_Call) Return(articleDetails *ArticleDetails, err error) *MockService_GetBySlug_Call {
	_c.Call.Return(articleDetails, err)
	return _c
}

func (_c *MockService_GetBySlug_Call) RunAndReturn(run func(ctx context.Context, slug string) (*ArticleDetails, error)) *MockService_GetBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// ListPreviews provides a mock function for the type MockService
func (_mock *MockService) ListPreviews(ctx context.Context, pageSize int, opts ...ListPreviewsOption) ([]ArticlePreview, string, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, pageSize, opts)
	} else {
		tmpRet = _mock.Called(ctx, pageSize)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListPreviews")
	}

	var r0 []ArticlePreview
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, ...ListPreviewsOption) ([]ArticlePreview, string, error)); ok {
		return returnFunc(ctx, pageSize, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, ...ListPreviewsOption) []ArticlePreview); ok {
		r0 = returnFunc(ctx, pageSize, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ArticlePreview)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, ...ListPreviewsOption) string); ok {
		r1 = returnFunc(ctx, pageSize, opts...)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int, ...ListPreviewsOption) error); ok {
		r2 = returnFunc(ctx, pageSize, opts...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockService_ListPreviews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPreviews'
type MockService_ListPreviews_Call struct {
	*mock.Call
}

// ListPreviews is a helper method to define mock.On call
//   - ctx context.Context
//   - pageSize int
//   - opts ...ListPreviewsOption
func (_e *MockService_Expecter) ListPreviews(ctx interface{}, pageSize interface{}, opts ...interface{}) *MockService_ListPreviews_Call {
	return &MockService_ListPreviews_Call{Call: _e.mock.On("ListPreviews",
		append([]interface{}{ctx, pageSize}, opts...)...)}
}

func (_c *MockService_ListPreviews_Call) Run(run func(ctx context.Context, pageSize int, opts ...ListPreviewsOption)) *MockService_ListPreviews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []ListPreviewsOption
		var variadicArgs []ListPreviewsOption
		if len(args) > 2 {
			variadicArgs = args[2].([]ListPreviewsOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockService_ListPreviews_Call) Return(articlePreviews []ArticlePreview, s string, err error) *MockService_ListPreviews_Call {
	_c.Call.Return(articlePreviews, s, err)
	return _c
}

func (_c *MockService_ListPreviews_Call) RunAndReturn(run func(ctx context.Context, pageSize int, opts ...ListPreviewsOption) ([]ArticlePreview, string, error)) *MockService_ListPreviews_Call {
	_c.Call.Return(run)
	return _c
}
