// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tuananhlai/brevity-go/internal/model"
	"github.com/tuananhlai/brevity-go/internal/repository"
)

// NewMockArticleService creates a new instance of MockArticleService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockArticleService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockArticleService {
	mock := &MockArticleService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockArticleService is an autogenerated mock type for the ArticleService type
type MockArticleService struct {
	mock.Mock
}

type MockArticleService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockArticleService) EXPECT() *MockArticleService_Expecter {
	return &MockArticleService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockArticleService
func (_mock *MockArticleService) Create(ctx context.Context, article *model.Article) error {
	ret := _mock.Called(ctx, article)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Article) error); ok {
		r0 = returnFunc(ctx, article)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockArticleService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockArticleService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx
//   - article
func (_e *MockArticleService_Expecter) Create(ctx interface{}, article interface{}) *MockArticleService_Create_Call {
	return &MockArticleService_Create_Call{Call: _e.mock.On("Create", ctx, article)}
}

func (_c *MockArticleService_Create_Call) Run(run func(ctx context.Context, article *model.Article)) *MockArticleService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Article))
	})
	return _c
}

func (_c *MockArticleService_Create_Call) Return(err error) *MockArticleService_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockArticleService_Create_Call) RunAndReturn(run func(ctx context.Context, article *model.Article) error) *MockArticleService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetBySlug provides a mock function for the type MockArticleService
func (_mock *MockArticleService) GetBySlug(ctx context.Context, slug string) (*model.ArticleDetails, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetBySlug")
	}

	var r0 *model.ArticleDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.ArticleDetails, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.ArticleDetails); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ArticleDetails)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockArticleService_GetBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySlug'
type MockArticleService_GetBySlug_Call struct {
	*mock.Call
}

// GetBySlug is a helper method to define mock.On call
//   - ctx
//   - slug
func (_e *MockArticleService_Expecter) GetBySlug(ctx interface{}, slug interface{}) *MockArticleService_GetBySlug_Call {
	return &MockArticleService_GetBySlug_Call{Call: _e.mock.On("GetBySlug", ctx, slug)}
}

func (_c *MockArticleService_GetBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockArticleService_GetBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockArticleService_GetBySlug_Call) Return(articleDetails *model.ArticleDetails, err error) *MockArticleService_GetBySlug_Call {
	_c.Call.Return(articleDetails, err)
	return _c
}

func (_c *MockArticleService_GetBySlug_Call) RunAndReturn(run func(ctx context.Context, slug string) (*model.ArticleDetails, error)) *MockArticleService_GetBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// ListPreviews provides a mock function for the type MockArticleService
func (_mock *MockArticleService) ListPreviews(ctx context.Context, pageSize int, opts ...repository.ListPreviewsOption) ([]model.ArticlePreview, string, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, pageSize, opts)
	} else {
		tmpRet = _mock.Called(ctx, pageSize)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListPreviews")
	}

	var r0 []model.ArticlePreview
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, ...repository.ListPreviewsOption) ([]model.ArticlePreview, string, error)); ok {
		return returnFunc(ctx, pageSize, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, ...repository.ListPreviewsOption) []model.ArticlePreview); ok {
		r0 = returnFunc(ctx, pageSize, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ArticlePreview)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, ...repository.ListPreviewsOption) string); ok {
		r1 = returnFunc(ctx, pageSize, opts...)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int, ...repository.ListPreviewsOption) error); ok {
		r2 = returnFunc(ctx, pageSize, opts...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockArticleService_ListPreviews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPreviews'
type MockArticleService_ListPreviews_Call struct {
	*mock.Call
}

// ListPreviews is a helper method to define mock.On call
//   - ctx
//   - pageSize
//   - opts
func (_e *MockArticleService_Expecter) ListPreviews(ctx interface{}, pageSize interface{}, opts ...interface{}) *MockArticleService_ListPreviews_Call {
	return &MockArticleService_ListPreviews_Call{Call: _e.mock.On("ListPreviews",
		append([]interface{}{ctx, pageSize}, opts...)...)}
}

func (_c *MockArticleService_ListPreviews_Call) Run(run func(ctx context.Context, pageSize int, opts ...repository.ListPreviewsOption)) *MockArticleService_ListPreviews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]repository.ListPreviewsOption)
		run(args[0].(context.Context), args[1].(int), variadicArgs...)
	})
	return _c
}

func (_c *MockArticleService_ListPreviews_Call) Return(articlePreviews []model.ArticlePreview, s string, err error) *MockArticleService_ListPreviews_Call {
	_c.Call.Return(articlePreviews, s, err)
	return _c
}

func (_c *MockArticleService_ListPreviews_Call) RunAndReturn(run func(ctx context.Context, pageSize int, opts ...repository.ListPreviewsOption) ([]model.ArticlePreview, string, error)) *MockArticleService_ListPreviews_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Login(ctx context.Context, emailOrUsername string, password string) (*LoginReturn, error) {
	ret := _mock.Called(ctx, emailOrUsername, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *LoginReturn
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*LoginReturn, error)); ok {
		return returnFunc(ctx, emailOrUsername, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *LoginReturn); ok {
		r0 = returnFunc(ctx, emailOrUsername, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*LoginReturn)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, emailOrUsername, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx
//   - emailOrUsername
//   - password
func (_e *MockAuthService_Expecter) Login(ctx interface{}, emailOrUsername interface{}, password interface{}) *MockAuthService_Login_Call {
	return &MockAuthService_Login_Call{Call: _e.mock.On("Login", ctx, emailOrUsername, password)}
}

func (_c *MockAuthService_Login_Call) Run(run func(ctx context.Context, emailOrUsername string, password string)) *MockAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAuthService_Login_Call) Return(loginReturn *LoginReturn, err error) *MockAuthService_Login_Call {
	_c.Call.Return(loginReturn, err)
	return _c
}

func (_c *MockAuthService_Login_Call) RunAndReturn(run func(ctx context.Context, emailOrUsername string, password string) (*LoginReturn, error)) *MockAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshAccessToken provides a mock function for the type MockAuthService
func (_mock *MockAuthService) RefreshAccessToken(ctx context.Context, refreshToken string) (string, error) {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshAccessToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_RefreshAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshAccessToken'
type MockAuthService_RefreshAccessToken_Call struct {
	*mock.Call
}

// RefreshAccessToken is a helper method to define mock.On call
//   - ctx
//   - refreshToken
func (_e *MockAuthService_Expecter) RefreshAccessToken(ctx interface{}, refreshToken interface{}) *MockAuthService_RefreshAccessToken_Call {
	return &MockAuthService_RefreshAccessToken_Call{Call: _e.mock.On("RefreshAccessToken", ctx, refreshToken)}
}

func (_c *MockAuthService_RefreshAccessToken_Call) Run(run func(ctx context.Context, refreshToken string)) *MockAuthService_RefreshAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthService_RefreshAccessToken_Call) Return(s string, err error) *MockAuthService_RefreshAccessToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAuthService_RefreshAccessToken_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) (string, error)) *MockAuthService_RefreshAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Register(ctx context.Context, email string, username string, password string) error {
	ret := _mock.Called(ctx, email, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, email, username, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx
//   - email
//   - username
//   - password
func (_e *MockAuthService_Expecter) Register(ctx interface{}, email interface{}, username interface{}, password interface{}) *MockAuthService_Register_Call {
	return &MockAuthService_Register_Call{Call: _e.mock.On("Register", ctx, email, username, password)}
}

func (_c *MockAuthService_Register_Call) Run(run func(ctx context.Context, email string, username string, password string)) *MockAuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockAuthService_Register_Call) Return(err error) *MockAuthService_Register_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthService_Register_Call) RunAndReturn(run func(ctx context.Context, email string, username string, password string) error) *MockAuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}
