// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package store

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// CreateArticle provides a mock function for the type MockStore
func (_mock *MockStore) CreateArticle(ctx context.Context, article *Article) error {
	ret := _mock.Called(ctx, article)

	if len(ret) == 0 {
		panic("no return value specified for CreateArticle")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Article) error); ok {
		r0 = returnFunc(ctx, article)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_CreateArticle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateArticle'
type MockStore_CreateArticle_Call struct {
	*mock.Call
}

// CreateArticle is a helper method to define mock.On call
//   - ctx context.Context
//   - article *Article
func (_e *MockStore_Expecter) CreateArticle(ctx interface{}, article interface{}) *MockStore_CreateArticle_Call {
	return &MockStore_CreateArticle_Call{Call: _e.mock.On("CreateArticle", ctx, article)}
}

func (_c *MockStore_CreateArticle_Call) Run(run func(ctx context.Context, article *Article)) *MockStore_CreateArticle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Article
		if args[1] != nil {
			arg1 = args[1].(*Article)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_CreateArticle_Call) Return(err error) *MockStore_CreateArticle_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_CreateArticle_Call) RunAndReturn(run func(ctx context.Context, article *Article) error) *MockStore_CreateArticle_Call {
	_c.Call.Return(run)
	return _c
}

// CreateLLMAPIKey provides a mock function for the type MockStore
func (_mock *MockStore) CreateLLMAPIKey(ctx context.Context, apiKey CreateLLMAPIKeyParams) (*OpenRouterAPIKey, error) {
	ret := _mock.Called(ctx, apiKey)

	if len(ret) == 0 {
		panic("no return value specified for CreateLLMAPIKey")
	}

	var r0 *OpenRouterAPIKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateLLMAPIKeyParams) (*OpenRouterAPIKey, error)); ok {
		return returnFunc(ctx, apiKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateLLMAPIKeyParams) *OpenRouterAPIKey); ok {
		r0 = returnFunc(ctx, apiKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*OpenRouterAPIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, CreateLLMAPIKeyParams) error); ok {
		r1 = returnFunc(ctx, apiKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CreateLLMAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLLMAPIKey'
type MockStore_CreateLLMAPIKey_Call struct {
	*mock.Call
}

// CreateLLMAPIKey is a helper method to define mock.On call
//   - ctx context.Context
//   - apiKey CreateLLMAPIKeyParams
func (_e *MockStore_Expecter) CreateLLMAPIKey(ctx interface{}, apiKey interface{}) *MockStore_CreateLLMAPIKey_Call {
	return &MockStore_CreateLLMAPIKey_Call{Call: _e.mock.On("CreateLLMAPIKey", ctx, apiKey)}
}

func (_c *MockStore_CreateLLMAPIKey_Call) Run(run func(ctx context.Context, apiKey CreateLLMAPIKeyParams)) *MockStore_CreateLLMAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 CreateLLMAPIKeyParams
		if args[1] != nil {
			arg1 = args[1].(CreateLLMAPIKeyParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_CreateLLMAPIKey_Call) Return(openRouterAPIKey *OpenRouterAPIKey, err error) *MockStore_CreateLLMAPIKey_Call {
	_c.Call.Return(openRouterAPIKey, err)
	return _c
}

func (_c *MockStore_CreateLLMAPIKey_Call) RunAndReturn(run func(ctx context.Context, apiKey CreateLLMAPIKeyParams) (*OpenRouterAPIKey, error)) *MockStore_CreateLLMAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockStore
func (_mock *MockStore) CreateUser(ctx context.Context, params CreateUserParams) (*User, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateUserParams) (*User, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateUserParams) *User); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, CreateUserParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockStore_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - params CreateUserParams
func (_e *MockStore_Expecter) CreateUser(ctx interface{}, params interface{}) *MockStore_CreateUser_Call {
	return &MockStore_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, params)}
}

func (_c *MockStore_CreateUser_Call) Run(run func(ctx context.Context, params CreateUserParams)) *MockStore_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 CreateUserParams
		if args[1] != nil {
			arg1 = args[1].(CreateUserParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_CreateUser_Call) Return(user *User, err error) *MockStore_CreateUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockStore_CreateUser_Call) RunAndReturn(run func(ctx context.Context, params CreateUserParams) (*User, error)) *MockStore_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetArticleBySlug provides a mock function for the type MockStore
func (_mock *MockStore) GetArticleBySlug(ctx context.Context, slug string) (*ArticleDetails, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetArticleBySlug")
	}

	var r0 *ArticleDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ArticleDetails, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ArticleDetails); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ArticleDetails)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetArticleBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetArticleBySlug'
type MockStore_GetArticleBySlug_Call struct {
	*mock.Call
}

// GetArticleBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockStore_Expecter) GetArticleBySlug(ctx interface{}, slug interface{}) *MockStore_GetArticleBySlug_Call {
	return &MockStore_GetArticleBySlug_Call{Call: _e.mock.On("GetArticleBySlug", ctx, slug)}
}

func (_c *MockStore_GetArticleBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockStore_GetArticleBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetArticleBySlug_Call) Return(articleDetails *ArticleDetails, err error) *MockStore_GetArticleBySlug_Call {
	_c.Call.Return(articleDetails, err)
	return _c
}

func (_c *MockStore_GetArticleBySlug_Call) RunAndReturn(run func(ctx context.Context, slug string) (*ArticleDetails, error)) *MockStore_GetArticleBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type MockStore
func (_mock *MockStore) GetUser(ctx context.Context, emailOrUsername string) (*User, error) {
	ret := _mock.Called(ctx, emailOrUsername)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*User, error)); ok {
		return returnFunc(ctx, emailOrUsername)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *User); ok {
		r0 = returnFunc(ctx, emailOrUsername)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, emailOrUsername)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockStore_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - emailOrUsername string
func (_e *MockStore_Expecter) GetUser(ctx interface{}, emailOrUsername interface{}) *MockStore_GetUser_Call {
	return &MockStore_GetUser_Call{Call: _e.mock.On("GetUser", ctx, emailOrUsername)}
}

func (_c *MockStore_GetUser_Call) Run(run func(ctx context.Context, emailOrUsername string)) *MockStore_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetUser_Call) Return(user *User, err error) *MockStore_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockStore_GetUser_Call) RunAndReturn(run func(ctx context.Context, emailOrUsername string) (*User, error)) *MockStore_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockStore
func (_mock *MockStore) GetUserByID(ctx context.Context, userID string) (*User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockStore_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockStore_Expecter) GetUserByID(ctx interface{}, userID interface{}) *MockStore_GetUserByID_Call {
	return &MockStore_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, userID)}
}

func (_c *MockStore_GetUserByID_Call) Run(run func(ctx context.Context, userID string)) *MockStore_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetUserByID_Call) Return(user *User, err error) *MockStore_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockStore_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, userID string) (*User, error)) *MockStore_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListArticlesPreviews provides a mock function for the type MockStore
func (_mock *MockStore) ListArticlesPreviews(ctx context.Context) ([]ArticlePreview, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListArticlesPreviews")
	}

	var r0 []ArticlePreview
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]ArticlePreview, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []ArticlePreview); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ArticlePreview)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ListArticlesPreviews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListArticlesPreviews'
type MockStore_ListArticlesPreviews_Call struct {
	*mock.Call
}

// ListArticlesPreviews is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) ListArticlesPreviews(ctx interface{}) *MockStore_ListArticlesPreviews_Call {
	return &MockStore_ListArticlesPreviews_Call{Call: _e.mock.On("ListArticlesPreviews", ctx)}
}

func (_c *MockStore_ListArticlesPreviews_Call) Run(run func(ctx context.Context)) *MockStore_ListArticlesPreviews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_ListArticlesPreviews_Call) Return(results []ArticlePreview, err error) *MockStore_ListArticlesPreviews_Call {
	_c.Call.Return(results, err)
	return _c
}

func (_c *MockStore_ListArticlesPreviews_Call) RunAndReturn(run func(ctx context.Context) ([]ArticlePreview, error)) *MockStore_ListArticlesPreviews_Call {
	_c.Call.Return(run)
	return _c
}

// ListDigitalAuthorsWithArticleSlugs provides a mock function for the type MockStore
func (_mock *MockStore) ListDigitalAuthorsWithArticleSlugs(ctx context.Context) ([]*DigitalAuthorWithArticleSlugs, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListDigitalAuthorsWithArticleSlugs")
	}

	var r0 []*DigitalAuthorWithArticleSlugs
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*DigitalAuthorWithArticleSlugs, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*DigitalAuthorWithArticleSlugs); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*DigitalAuthorWithArticleSlugs)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ListDigitalAuthorsWithArticleSlugs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDigitalAuthorsWithArticleSlugs'
type MockStore_ListDigitalAuthorsWithArticleSlugs_Call struct {
	*mock.Call
}

// ListDigitalAuthorsWithArticleSlugs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) ListDigitalAuthorsWithArticleSlugs(ctx interface{}) *MockStore_ListDigitalAuthorsWithArticleSlugs_Call {
	return &MockStore_ListDigitalAuthorsWithArticleSlugs_Call{Call: _e.mock.On("ListDigitalAuthorsWithArticleSlugs", ctx)}
}

func (_c *MockStore_ListDigitalAuthorsWithArticleSlugs_Call) Run(run func(ctx context.Context)) *MockStore_ListDigitalAuthorsWithArticleSlugs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_ListDigitalAuthorsWithArticleSlugs_Call) Return(digitalAuthorWithArticleSlugss []*DigitalAuthorWithArticleSlugs, err error) *MockStore_ListDigitalAuthorsWithArticleSlugs_Call {
	_c.Call.Return(digitalAuthorWithArticleSlugss, err)
	return _c
}

func (_c *MockStore_ListDigitalAuthorsWithArticleSlugs_Call) RunAndReturn(run func(ctx context.Context) ([]*DigitalAuthorWithArticleSlugs, error)) *MockStore_ListDigitalAuthorsWithArticleSlugs_Call {
	_c.Call.Return(run)
	return _c
}

// ListLLMAPIKeysByUserID provides a mock function for the type MockStore
func (_mock *MockStore) ListLLMAPIKeysByUserID(ctx context.Context, userID string) ([]*OpenRouterAPIKey, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListLLMAPIKeysByUserID")
	}

	var r0 []*OpenRouterAPIKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*OpenRouterAPIKey, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*OpenRouterAPIKey); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*OpenRouterAPIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ListLLMAPIKeysByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListLLMAPIKeysByUserID'
type MockStore_ListLLMAPIKeysByUserID_Call struct {
	*mock.Call
}

// ListLLMAPIKeysByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockStore_Expecter) ListLLMAPIKeysByUserID(ctx interface{}, userID interface{}) *MockStore_ListLLMAPIKeysByUserID_Call {
	return &MockStore_ListLLMAPIKeysByUserID_Call{Call: _e.mock.On("ListLLMAPIKeysByUserID", ctx, userID)}
}

func (_c *MockStore_ListLLMAPIKeysByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockStore_ListLLMAPIKeysByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_ListLLMAPIKeysByUserID_Call) Return(openRouterAPIKeys []*OpenRouterAPIKey, err error) *MockStore_ListLLMAPIKeysByUserID_Call {
	_c.Call.Return(openRouterAPIKeys, err)
	return _c
}

func (_c *MockStore_ListLLMAPIKeysByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*OpenRouterAPIKey, error)) *MockStore_ListLLMAPIKeysByUserID_Call {
	_c.Call.Return(run)
	return _c
}
