package utils

import (
	"encoding/base64"
	"encoding/json"
)

// GeneratePageToken creates a page token from the given value. The value must be JSON-serializable.
func GeneratePageToken(v any) (string, error) {
	json, err := json.Marshal(v)
	if err != nil {
		return "", err
	}

	return base64.StdEncoding.EncodeToString(json), nil
}

// ParsePageToken parses a page token into the given variable. The token must be generated by generatePageToken.
//
// example:
//
//	var v ListPreviewsPageToken{}
//	err := ParsePageToken(token, &v)
//	if err != nil {
//		return err
//	}
func ParsePageToken(token string, v any) error {
	jsonString, err := base64.StdEncoding.DecodeString(token)
	if err != nil {
		return err
	}

	return json.Unmarshal(jsonString, v)
}
