// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tuananhlai/brevity-go/internal/repository"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// GetCurrentUser provides a mock function for the type MockService
func (_mock *MockService) GetCurrentUser(ctx context.Context, userID string) (*repository.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentUser")
	}

	var r0 *repository.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*repository.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *repository.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetCurrentUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentUser'
type MockService_GetCurrentUser_Call struct {
	*mock.Call
}

// GetCurrentUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockService_Expecter) GetCurrentUser(ctx interface{}, userID interface{}) *MockService_GetCurrentUser_Call {
	return &MockService_GetCurrentUser_Call{Call: _e.mock.On("GetCurrentUser", ctx, userID)}
}

func (_c *MockService_GetCurrentUser_Call) Run(run func(ctx context.Context, userID string)) *MockService_GetCurrentUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetCurrentUser_Call) Return(user *repository.User, err error) *MockService_GetCurrentUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockService_GetCurrentUser_Call) RunAndReturn(run func(ctx context.Context, userID string) (*repository.User, error)) *MockService_GetCurrentUser_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockService
func (_mock *MockService) Login(ctx context.Context, emailOrUsername string, password string) (*LoginResult, error) {
	ret := _mock.Called(ctx, emailOrUsername, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *LoginResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*LoginResult, error)); ok {
		return returnFunc(ctx, emailOrUsername, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *LoginResult); ok {
		r0 = returnFunc(ctx, emailOrUsername, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*LoginResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, emailOrUsername, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - emailOrUsername string
//   - password string
func (_e *MockService_Expecter) Login(ctx interface{}, emailOrUsername interface{}, password interface{}) *MockService_Login_Call {
	return &MockService_Login_Call{Call: _e.mock.On("Login", ctx, emailOrUsername, password)}
}

func (_c *MockService_Login_Call) Run(run func(ctx context.Context, emailOrUsername string, password string)) *MockService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Login_Call) Return(loginResult *LoginResult, err error) *MockService_Login_Call {
	_c.Call.Return(loginResult, err)
	return _c
}

func (_c *MockService_Login_Call) RunAndReturn(run func(ctx context.Context, emailOrUsername string, password string) (*LoginResult, error)) *MockService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockService
func (_mock *MockService) Register(ctx context.Context, email string, username string, password string) error {
	ret := _mock.Called(ctx, email, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, email, username, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - username string
//   - password string
func (_e *MockService_Expecter) Register(ctx interface{}, email interface{}, username interface{}, password interface{}) *MockService_Register_Call {
	return &MockService_Register_Call{Call: _e.mock.On("Register", ctx, email, username, password)}
}

func (_c *MockService_Register_Call) Run(run func(ctx context.Context, email string, username string, password string)) *MockService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_Register_Call) Return(err error) *MockService_Register_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Register_Call) RunAndReturn(run func(ctx context.Context, email string, username string, password string) error) *MockService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyAccessToken provides a mock function for the type MockService
func (_mock *MockService) VerifyAccessToken(ctx context.Context, accessToken string) (string, error) {
	ret := _mock.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for VerifyAccessToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, accessToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, accessToken)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accessToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_VerifyAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyAccessToken'
type MockService_VerifyAccessToken_Call struct {
	*mock.Call
}

// VerifyAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *MockService_Expecter) VerifyAccessToken(ctx interface{}, accessToken interface{}) *MockService_VerifyAccessToken_Call {
	return &MockService_VerifyAccessToken_Call{Call: _e.mock.On("VerifyAccessToken", ctx, accessToken)}
}

func (_c *MockService_VerifyAccessToken_Call) Run(run func(ctx context.Context, accessToken string)) *MockService_VerifyAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_VerifyAccessToken_Call) Return(s string, err error) *MockService_VerifyAccessToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockService_VerifyAccessToken_Call) RunAndReturn(run func(ctx context.Context, accessToken string) (string, error)) *MockService_VerifyAccessToken_Call {
	_c.Call.Return(run)
	return _c
}
