// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/jmoiron/sqlx"
	"github.com/tuananhlai/brevity-go/internal/controller"
	"github.com/tuananhlai/brevity-go/internal/repository"
	"github.com/tuananhlai/brevity-go/internal/service"
)

// Injectors from wire.go:

func InitializeArticleController(db *sqlx.DB) *controller.ArticleController {
	articleRepository := repository.NewArticleRepository(db)
	articleService := service.NewArticleService(articleRepository)
	articleController := controller.NewArticleController(articleService)
	return articleController
}

func InitializeAuthController(db *sqlx.DB, opts ...service.AuthServiceOption) *controller.AuthController {
	authRepository := repository.NewAuthRepository(db)
	authService := service.NewAuthService(authRepository, opts...)
	authController := controller.NewAuthController(authService)
	return authController
}
