name: OpenAPI Diff
on:
  pull_request:
    paths:
      - "api/**"

jobs:
  api-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out head branch
        uses: actions/checkout@v4

      - name: Check out base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          path: base

      - name: Run OpenAPI Diff (from HEAD revision)
        uses: ./.github/actions/openapi-diff
        with:
          head-spec: ./api/openapi.yml
          base-spec: ./base/api/openapi.yml
