name: OpenAPI Diff
on:
  pull_request:
    paths:
      - "api/**"

jobs:
  api-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check out base openapi.yml
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          path: api/openapi_base_branch.yml
          sparse-checkout: api/openapi.yml
          sparse-checkout-cone-mode: false

      - name: Run OpenAPI Diff
        uses: ./.github/actions/openapi-diff
        with:
          head-spec: ./api/openapi.yml
          base-spec: ./api/openapi_base_branch.yml
